version: '3.1'
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: bit.url_db
    environment:
      POSTGRES_USER: bit
      POSTGRES_PASSWORD: bit
      POSTGRES_DB: bit
    volumes:
      - bit.url_vol:/var/lib/postgresql/data
    ports:
      - "8000:5432"
volumes:
  bit.url_vol:
