version: '3.1'
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: bit.url_db
    environment:
      POSTGRES_USER: bit
      POSTGRES_PASSWORD: bit
      POSTGRES_DB: bit
    volumes:
      - bit.url_vol:/var/lib/postgresql/data
    ports:
      - "8000:5432"

  redis:
    image: redis:7.2.1
    container_name: bit_url_cache
    command: [ "redis-server", "--requirepass biturl" ]
    volumes:
      - bit_url_cache_data:/data
    ports:
      - "8001:6379"
volumes:
  bit.url_vol:
  bit_url_cache_data:
