server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/bit
    username: bit
    password: bit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

