server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/bit
    username: bit
    password: bit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Redis Property
  data:
    redis:
      host: localhost
      port: 8001
      password: biturl
      timeout: 60000

